language: ruby
rvm:
- 2.1.0
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rake db:test:prepare
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: Aco51AMTtzmD3OhYUPtddhI7SEgRV3BiiuPEKSsp0DLv/HymbtKNX9ZArMxoD85uHaOTtGnsxvKwTYXN7cD02IpMEMcjMhNtCWzMwa8DPlpxf2Gqtu83ksxrR2jXW7GozJtepIgNdCTJEEd2JX0aZTVeJOsiFxlVNLlnzAGsMhM=
  app: adthul-portfolio
  on:
    repo: adthul/portfolio
